# Generated by Django 5.1.3 on 2024-12-05 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0008_customuser_bio_customuser_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(default='default_roll_no', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 9, 41, 55, 211226, tzinfo=datetime.timezone.utc)),
        ),
    ]
