# Generated by Django 5.1.3 on 2024-12-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0009_alter_customuser_roll_no_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 9, 43, 26, 724545, tzinfo=datetime.timezone.utc)),
        ),
    ]
