# Generated by Django 5.1.3 on 2024-12-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0011_hosttable_alter_otp_expired_at_studenttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostTable',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 14, 24, 32, 755131, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='StudentTable',
        ),
    ]
