# Generated by Django 5.1.3 on 2024-12-06 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0014_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='practical_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.CharField(default='default_quiz_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 6, 28, 42, 542200, tzinfo=datetime.timezone.utc)),
        ),
    ]
