# Generated by Django 5.1.3 on 2024-12-06 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0015_quiz_practical_no_quiz_quiz_id_alter_otp_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='practical_no',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 7, 12, 41, 606449, tzinfo=datetime.timezone.utc)),
        ),
    ]
