# Generated by Django 5.1.3 on 2024-12-06 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0016_remove_quiz_practical_no_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(default='Default Question'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 8, 7, 29, 291710, tzinfo=datetime.timezone.utc)),
        ),
    ]
