# Generated by Django 5.1.3 on 2024-12-06 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSA', '0018_alter_otp_expired_at_alter_quiz_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mcqs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('practical_no', models.PositiveIntegerField(default=0)),
                ('batch', models.CharField(choices=[('A', 'Batch A'), ('B', 'Batch B'), ('C', 'Batch C')], default='A', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 10, 45, 37, 74404, tzinfo=datetime.timezone.utc)),
        ),
    ]
